// jshint esversion: 6, node: true
"use strict";
if (typeof require !== 'undefined' && typeof equal === 'undefined') {
    var equal = require( './esequal' );
}
console.log('equal()');

console.log( 'must be a function' );
console.assert( typeof equal === 'function' );
console.assert( equal.length === 3 );
console.assert( equal.name === 'equal' );
console.log('-- Ok');

console.log( 'should make strict comparison' );
console.assert(  equal( "", "" ) );
console.assert(  equal( "", "" ) === equal.VALUE_AND_TYPE );
console.assert( !equal( "Hello", "hello" ) );
console.assert(  equal( "Hello", "hello" ) === equal.NOT_EQUAL );
console.assert(  equal( "Hello", "Hello" ) );
console.assert(  equal( "Hello", "Hello" ) === equal.VALUE_AND_TYPE );
console.assert(  equal( true, true ) );
console.assert(  equal( true, true ) === equal.VALUE_AND_TYPE );
console.assert(  equal( false, false ) );
console.assert(  equal( false, false ) === equal.VALUE_AND_TYPE );
console.assert( !equal( true, false ) );
console.assert(  equal( true, false ) === equal.NOT_EQUAL);
console.assert( !equal( true, 1 ) );
console.assert(  equal( true, 1 ) === equal.NOT_EQUAL );
console.assert( !equal( true, 0 ) );
console.assert(  equal( true, 0 ) === equal.NOT_EQUAL );
console.assert( !equal( true, "hello" ) );
console.assert(  equal( true, "hello" ) === equal.NOT_EQUAL );
console.assert( !equal( true, '' ) );
console.assert(  equal( true, '' ) === equal.NOT_EQUAL );
console.assert( !equal( false, 0 ) );
console.assert(  equal( false, 0 ) === equal.NOT_EQUAL );
console.assert( !equal( false, "" ) );
console.assert(  equal( false, "" ) === equal.NOT_EQUAL );
console.assert( !equal( false, "hello" ) );
console.assert(  equal( false, "hello" ) === equal.NOT_EQUAL );
console.assert( !equal( null, 0 ) );
console.assert(  equal( null, 0 ) === equal.NOT_EQUAL );
console.assert(  equal( null, null ) );
console.assert(  equal( null, null ) === equal.VALUE_AND_TYPE );
console.assert( !equal( null, "null" ) );
console.assert(  equal( null, "null" ) === equal.NOT_EQUAL );
console.assert(  equal( 1, 1 ) );
console.assert(  equal( 1, 1 ) === equal.VALUE_AND_TYPE );
console.assert( !equal( 1, 0 ) );
console.assert(  equal( 1, 0 ) === equal.NOT_EQUAL );
console.assert( !equal( 1, "1" ) );
console.assert(  equal( 1, "1" ) === equal.NOT_EQUAL );
console.assert( !equal( 1, "0" )  );
console.assert(  equal( 1, "0" ) === equal.NOT_EQUAL );
console.assert( !equal( 1.0001, 1.00009 ) );
console.assert(  equal( 1.0001, 1.00009 ) === equal.NOT_EQUAL );
console.assert(  equal( 1.0001, 1.0001 ) );
console.assert(  equal( 1.0001, 1.0001 ) === equal.VALUE_AND_TYPE );
console.assert( !equal( 1.0001, '1.00009' ) );
console.assert(  equal( 1.0001, '1.00009' ) === equal.NOT_EQUAL );
console.assert( !equal( 1.0001, '1.0001' ) );
console.assert(  equal( 1.0001, '1.0001' ) === equal.NOT_EQUAL );
console.assert(  equal( undefined, undefined ) );
console.assert(  equal( undefined, undefined ) === equal.VALUE_AND_TYPE );
console.assert( !equal( undefined, "" ) );
console.assert(  equal( undefined, "" ) === equal.NOT_EQUAL );
console.assert( !equal( undefined, 1 ) );
console.assert(  equal( undefined, 1 ) === equal.NOT_EQUAL );
console.assert( !equal( undefined, false ) );
console.assert(  equal( undefined, false ) === equal.NOT_EQUAL );
console.assert( !equal( undefined, null ) );
console.assert(  equal( undefined, null ) === equal.NOT_EQUAL );
console.assert( !equal( undefined, {} ) );
console.assert(  equal( undefined, {} ) === equal.NOT_EQUAL );
console.log( '-- Ok' );

console.log( 'should make a non strict comparison with the "nonStrict" options is true' );
console.assert( !equal( true, false, {nonStrict: true}  ) );
console.assert(  equal( true, 1, {nonStrict: true}  ) );
console.assert(  equal( true, 1, {nonStrict: true}  ) === equal.VALUE );
console.assert( !equal( true, 0, {nonStrict: true}  ) );
console.assert( !equal( true, -1, {nonStrict: true}  ) );
console.assert( !equal( true, "true", {nonStrict: true}  ) );
console.assert( !equal( true, "false", {nonStrict: true}  ) );
console.assert(  equal( true, "1", {nonStrict: true}  ) );
console.assert(  equal( true, "1", {nonStrict: true}  ) === equal.VALUE );
console.assert( !equal( true, "0", {nonStrict: true}  ) );
console.assert( !equal( true, "-1", {nonStrict: true}  ) );
console.assert( !equal( true, "", {nonStrict: true}  ) );
console.assert( !equal( true, null, {nonStrict: true}  ) );
console.assert( !equal( true, undefined, {nonStrict: true}  ) );
console.assert( !equal( true, Infinity, {nonStrict: true}  ) );
console.assert( !equal( true, -Infinity, {nonStrict: true}  ) );
console.assert( !equal( true, [], {nonStrict: true}  ) );
console.assert( !equal( true, {}, {nonStrict: true}  ) );
console.assert( !equal( true, [[]], {nonStrict: true}  ) );
console.assert( !equal( true, [0], {nonStrict: true}  ) );
console.assert(  equal( true, [1], {nonStrict: true}  ) );
console.assert(  equal( true, [1], {nonStrict: true}  ) === equal.VALUE );
console.assert( !equal( true, NaN, {nonStrict: true}  ) );
console.assert( !equal( false, 1, {nonStrict: true}  ) );
console.assert(  equal( false, 0, {nonStrict: true}  ) );
console.assert(  equal( false, 0, {nonStrict: true}  ) === equal.VALUE );
console.assert( !equal( false, -1, {nonStrict: true}  ) );
console.assert( !equal( false, "true", {nonStrict: true}  ) );
console.assert( !equal( false, "false", {nonStrict: true}  ) );
console.assert( !equal( false, "1", {nonStrict: true}  ) );
console.assert(  equal( false, "0", {nonStrict: true}  ) );
console.assert(  equal( false, "0", {nonStrict: true}  ) === equal.VALUE );
console.assert( !equal( false, "-1", {nonStrict: true}  ) );
console.assert(  equal( false, "", {nonStrict: true}  ) );
console.assert(  equal( false, "", {nonStrict: true}  ) === equal.VALUE );
console.assert( !equal( false, null, {nonStrict: true}  ) );
console.assert( !equal( false, undefined, {nonStrict: true}  ) );
console.assert( !equal( false, Infinity, {nonStrict: true}  ) );
console.assert( !equal( false, -Infinity, {nonStrict: true}  ) );
console.assert(  equal( false, [], {nonStrict: true}  ) );
console.assert(  equal( false, [], {nonStrict: true}  ) === equal.VALUE );
console.assert( !equal( false, {}, {nonStrict: true}  ) );
console.assert(  equal( false, [[]], {nonStrict: true} ) );
console.assert(  equal( false, [[]], {nonStrict: true} )  === equal.VALUE );
console.assert(  equal( false, [0], {nonStrict: true}  ) );
console.assert(  equal( false, [0], {nonStrict: true}  )  === equal.VALUE );
console.assert( !equal( false, [1], {nonStrict: true}  ) );
console.assert( !equal( false, NaN, {nonStrict: true}  ) );
console.assert( !equal( 1, 0, {nonStrict: true}  ) );
console.assert( !equal( 1, -1, {nonStrict: true}  ) );
console.assert( !equal( 1, "true", {nonStrict: true}  ) );
console.assert( !equal( 1, "false", {nonStrict: true}  ) );
console.assert(  equal( 1, "1", {nonStrict: true}  ) );
console.assert(  equal( 1, "1", {nonStrict: true}  ) === equal.VALUE );
console.assert( !equal( 1, "0", {nonStrict: true}  ) );
console.assert( !equal( 1, "-1", {nonStrict: true}  ) );
console.assert( !equal( 1, "", {nonStrict: true}  ) );
console.assert( !equal( 1, null, {nonStrict: true}  ) );
console.assert( !equal( 1, undefined, {nonStrict: true}  ) );
console.assert( !equal( 1, Infinity, {nonStrict: true}  ) );
console.assert( !equal( 1, -Infinity, {nonStrict: true}  ) );
console.assert( !equal( 1, [], {nonStrict: true}  ) );
console.assert( !equal( 1, {}, {nonStrict: true}  ) );
console.assert( !equal( 1, [[]], {nonStrict: true}  ) );
console.assert( !equal( 1, [0], {nonStrict: true}  ) );
console.assert(  equal( 1, [1], {nonStrict: true}  ) );
console.assert(  equal( 1, [1], {nonStrict: true}  ) === equal.VALUE );
console.assert( !equal( 1, NaN, {nonStrict: true}  ) );
console.assert( !equal( 0, -1, {nonStrict: true}  ) );
console.assert( !equal( 0, "true", {nonStrict: true}  ) );
console.assert( !equal( 0, "false", {nonStrict: true}  ) );
console.assert( !equal( 0, "1", {nonStrict: true}  ) );
console.assert(  equal( 0, "0", {nonStrict: true}  ) );
console.assert(  equal( 0, "0", {nonStrict: true}  ) === equal.VALUE );
console.assert( !equal( 0, "-1", {nonStrict: true}  ) );
console.assert(  equal( 0, "", {nonStrict: true}  ) );
console.assert(  equal( 0, "", {nonStrict: true}  ) === equal.VALUE );
console.assert( !equal( 0, null, {nonStrict: true}  ) );
console.assert( !equal( 0, undefined, {nonStrict: true}  ) );
console.assert( !equal( 0, Infinity, {nonStrict: true}  ) );
console.assert( !equal( 0, -Infinity, {nonStrict: true}  ) );
console.assert(  equal( 0, [], {nonStrict: true}  ) );
console.assert(  equal( 0, [], {nonStrict: true}  ) === equal.VALUE );
console.assert( !equal( 0, {}, {nonStrict: true}  ) );
console.assert(  equal( 0, [[]], {nonStrict: true}  ) );
console.assert(  equal( 0, [[]], {nonStrict: true}  ) === equal.VALUE );
console.assert(  equal( 0, [0], {nonStrict: true}  ) );
console.assert(  equal( 0, [0], {nonStrict: true}  ) === equal.VALUE );
console.assert( !equal( 0, [1], {nonStrict: true}  ) );
console.assert( !equal( 0, NaN, {nonStrict: true}  ) );
console.assert( !equal( -1, "true", {nonStrict: true}  ) );
console.assert( !equal( -1, "false", {nonStrict: true}  ) );
console.assert( !equal( -1, "1", {nonStrict: true}  ) );
console.assert( !equal( -1, "0", {nonStrict: true}  ) );
console.assert(  equal( -1, "-1", {nonStrict: true}  ) );
console.assert(  equal( -1, "-1", {nonStrict: true}  ) === equal.VALUE );
console.assert( !equal( -1, "", {nonStrict: true}  ) );
console.assert( !equal( -1, null, {nonStrict: true}  ) );
console.assert( !equal( -1, undefined, {nonStrict: true}  ) );
console.assert( !equal( -1, Infinity, {nonStrict: true}  ) );
console.assert( !equal( -1, -Infinity, {nonStrict: true}  ) );
console.assert( !equal( -1, [], {nonStrict: true}  ) );
console.assert( !equal( -1, {}, {nonStrict: true}  ) );
console.assert( !equal( -1, [[]], {nonStrict: true}  ) );
console.assert( !equal( -1, [0], {nonStrict: true}  ) );
console.assert( !equal( -1, [1], {nonStrict: true}  ) );
console.assert( !equal( -1, NaN, {nonStrict: true}  ) );
console.assert( !equal( "true", "false", {nonStrict: true}  ) );
console.assert( !equal( "true", "1", {nonStrict: true}  ) );
console.assert( !equal( "true", "0", {nonStrict: true}  ) );
console.assert( !equal( "true", "-1", {nonStrict: true}  ) );
console.assert( !equal( "true", "", {nonStrict: true}  ) );
console.assert( !equal( "true", null, {nonStrict: true}  ) );
console.assert( !equal( "true", undefined, {nonStrict: true}  ) );
console.assert( !equal( "true", Infinity, {nonStrict: true}  ) );
console.assert( !equal( "true", -Infinity, {nonStrict: true}  ) );
console.assert( !equal( "true", [], {nonStrict: true}  ) );
console.assert( !equal( "true", {}, {nonStrict: true}  ) );
console.assert( !equal( "true", [[]], {nonStrict: true}  ) );
console.assert( !equal( "true", [0], {nonStrict: true}  ) );
console.assert( !equal( "true", [1], {nonStrict: true}  ) );
console.assert( !equal( "true", NaN, {nonStrict: true}  ) );
console.assert( !equal( "false", "1", {nonStrict: true}  ) );
console.assert( !equal( "false", "0", {nonStrict: true}  ) );
console.assert( !equal( "false", "-1", {nonStrict: true}  ) );
console.assert( !equal( "false", "", {nonStrict: true}  ) );
console.assert( !equal( "false", null, {nonStrict: true}  ) );
console.assert( !equal( "false", undefined, {nonStrict: true}  ) );
console.assert( !equal( "false", Infinity, {nonStrict: true}  ) );
console.assert( !equal( "false", -Infinity, {nonStrict: true}  ) );
console.assert( !equal( "false", [], {nonStrict: true}  ) );
console.assert( !equal( "false", {}, {nonStrict: true}  ) );
console.assert( !equal( "false", [[]], {nonStrict: true}  ) );
console.assert( !equal( "false", [0], {nonStrict: true}  ) );
console.assert( !equal( "false", [1], {nonStrict: true}  ) );
console.assert( !equal( "false", NaN, {nonStrict: true}  ) );
console.assert( !equal( "1", "0", {nonStrict: true}  ) );
console.assert( !equal( "1", "-1", {nonStrict: true}  ) );
console.assert( !equal( "1", "", {nonStrict: true}  ) );
console.assert( !equal( "1", null, {nonStrict: true}  ) );
console.assert( !equal( "1", undefined, {nonStrict: true}  ) );
console.assert( !equal( "1", Infinity, {nonStrict: true}  ) );
console.assert( !equal( "1", -Infinity, {nonStrict: true}  ) );
console.assert( !equal( "1", [], {nonStrict: true}  ) );
console.assert( !equal( "1", {}, {nonStrict: true}  ) );
console.assert( !equal( "1", [[]], {nonStrict: true}  ) );
console.assert( !equal( "1", [0], {nonStrict: true}  ) );
console.assert(  equal( "1", [1], {nonStrict: true}  ) );
console.assert(  equal( "1", [1], {nonStrict: true}  ) === equal.VALUE );
console.assert( !equal( "1", NaN, {nonStrict: true}  ) );
console.assert( !equal( "0", "-1", {nonStrict: true}  ) );
console.assert( !equal( "0", "", {nonStrict: true}  ) );
console.assert( !equal( "0", null, {nonStrict: true}  ) );
console.assert( !equal( "0", undefined, {nonStrict: true}  ) );
console.assert( !equal( "0", Infinity, {nonStrict: true}  ) );
console.assert( !equal( "0", -Infinity, {nonStrict: true}  ) );
console.assert( !equal( "0", [], {nonStrict: true}  ) );
console.assert( !equal( "0", {}, {nonStrict: true}  ) );
console.assert( !equal( "0", [[]], {nonStrict: true}  ) );
console.assert(  equal( "0", [0], {nonStrict: true}  ) );
console.assert(  equal( "0", [0], {nonStrict: true}  ) === equal.VALUE );
console.assert( !equal( "0", [1], {nonStrict: true}  ) );
console.assert( !equal( "0", NaN, {nonStrict: true}  ) );
console.assert( !equal( "-1", "", {nonStrict: true}  ) );
console.assert( !equal( "-1", null, {nonStrict: true}  ) );
console.assert( !equal( "-1", undefined, {nonStrict: true}  ) );
console.assert( !equal( "-1", Infinity, {nonStrict: true}  ) );
console.assert( !equal( "-1", -Infinity, {nonStrict: true}  ) );
console.assert( !equal( "-1", [], {nonStrict: true}  ) );
console.assert( !equal( "-1", {}, {nonStrict: true}  ) );
console.assert( !equal( "-1", [[]], {nonStrict: true}  ) );
console.assert( !equal( "-1", [0], {nonStrict: true}  ) );
console.assert( !equal( "-1", [1], {nonStrict: true}  ) );
console.assert( !equal( "-1", NaN, {nonStrict: true}  ) );
console.assert( !equal( "", null, {nonStrict: true}  ) );
console.assert( !equal( "", undefined, {nonStrict: true}  ) );
console.assert( !equal( "", Infinity, {nonStrict: true}  ) );
console.assert( !equal( "", -Infinity, {nonStrict: true}  ) );
console.assert(  equal( "", [], {nonStrict: true}  ) );
console.assert(  equal( "", [], {nonStrict: true}  ) === equal.VALUE );
console.assert( !equal( "", {}, {nonStrict: true}  ) );
console.assert(  equal( "", [[]], {nonStrict: true}  ) );
console.assert(  equal( "", [[]], {nonStrict: true}  ) === equal.VALUE );
console.assert( !equal( "", [0], {nonStrict: true}  ) );
console.assert( !equal( "", [1], {nonStrict: true}  ) );
console.assert( !equal( "", NaN, {nonStrict: true}  ) );
console.assert(  equal( null, undefined, {nonStrict: true}  ) );
console.assert(  equal( null, undefined, {nonStrict: true}  ) === equal.VALUE );
console.assert( !equal( null, Infinity, {nonStrict: true}  ) );
console.assert( !equal( null, -Infinity, {nonStrict: true}  ) );
console.assert( !equal( null, [], {nonStrict: true}  ) );
console.assert( !equal( null, {}, {nonStrict: true}  ) );
console.assert( !equal( null, [[]], {nonStrict: true}  ) );
console.assert( !equal( null, [0], {nonStrict: true}  ) );
console.assert( !equal( null, [1], {nonStrict: true}  ) );
console.assert( !equal( null, NaN, {nonStrict: true}  ) );
console.assert( !equal( undefined, Infinity, {nonStrict: true}  ) );
console.assert( !equal( undefined, -Infinity, {nonStrict: true}  ) );
console.assert( !equal( undefined, [], {nonStrict: true}  ) );
console.assert( !equal( undefined, {}, {nonStrict: true}  ) );
console.assert( !equal( undefined, [[]], {nonStrict: true}  ) );
console.assert( !equal( undefined, [0], {nonStrict: true}  ) );
console.assert( !equal( undefined, [1], {nonStrict: true}  ) );
console.assert( !equal( undefined, NaN, {nonStrict: true}  ) );
console.assert( !equal( Infinity, -Infinity, {nonStrict: true}  ) );
console.assert( !equal( Infinity, [], {nonStrict: true}  ) );
console.assert( !equal( Infinity, {}, {nonStrict: true}  ) );
console.assert( !equal( Infinity, [[]], {nonStrict: true}  ) );
console.assert( !equal( Infinity, [0], {nonStrict: true}  ) );
console.assert( !equal( Infinity, [1], {nonStrict: true}  ) );
console.assert( !equal( Infinity, NaN, {nonStrict: true}  ) );
console.assert( !equal( -Infinity, [], {nonStrict: true}  ) );
console.assert( !equal( -Infinity, {}, {nonStrict: true}  ) );
console.assert( !equal( -Infinity, [[]], {nonStrict: true}  ) );
console.assert( !equal( -Infinity, [0], {nonStrict: true}  ) );
console.assert( !equal( -Infinity, [1], {nonStrict: true}  ) );
console.assert( !equal( -Infinity, NaN, {nonStrict: true}  ) );
console.assert( !equal( [], [[]], {nonStrict: true}  ) );
console.assert( !equal( [], [0], {nonStrict: true}  ) );
console.assert( !equal( [], [1], {nonStrict: true}  ) );
console.assert( !equal( [], NaN, {nonStrict: true}  ) );
console.assert( !equal( {}, [[]], {nonStrict: true}  ) );
console.assert( !equal( {}, [0], {nonStrict: true}  ) );
console.assert( !equal( {}, [1], {nonStrict: true}  ) );
console.assert( !equal( {}, NaN, {nonStrict: true}  ) );
console.assert( !equal( [[]], [1], {nonStrict: true}  ) );
console.assert( !equal( [[]], NaN, {nonStrict: true}  ) );
console.assert( !equal( [0], [1], {nonStrict: true}  ) );
console.assert( !equal( [0], NaN, {nonStrict: true}  ) );
console.assert( !equal( [1], NaN, {nonStrict: true}  ) );
console.log( '-- Ok' );

console.log( 'NaN vs NaN should be true');
console.assert(  equal( NaN, NaN ) );
console.assert(  equal( NaN, NaN ) === equal.VALUE_AND_TYPE );
console.assert(  equal( NaN, NaN, {nonStrict: true} ) );
console.assert(  equal( NaN, NaN, {nonStrict: true} ) === equal.VALUE_AND_TYPE );
console.log( '-- Ok' );

console.log( 'Date should be compared by its internal number' );
var date1   = new Date();
var date2   = date1;
var date3   = new Date( '2015-01-01' );
var date4   = new Date( date1.getTime() );
console.assert(  equal( date1, date2 ) );
console.assert(  equal( date1, date2 ) === equal.VALUE_AND_TYPE );
console.assert( !equal( date1, date3 ) );
console.assert(  equal( date1, date3 ) === equal.NOT_EQUAL );
console.assert(  equal( date1, date4 ) );
console.assert(  equal( date1, date4 ) === equal.VALUE_AND_TYPE );
console.log( '-- Ok' );

console.log( 'String wrapper should be compared as a string' );
// jshint -W053
var string1 = new String( 'hello' );
var string2 = string1;
var string3 = new String( 'other' );
var string4 = new String( 'hello' );
// jshint -W053
var string5 = 'hello';
var string6 = 'HELLO';
var string7 = 'HELLO';
console.assert(  equal( string1, string2 ) );
console.assert(  equal( string1, string2 ) === equal.VALUE_AND_TYPE );
console.assert( !equal( string1, string3 ) );
console.assert(  equal( string1, string3 ) === equal.NOT_EQUAL );
console.assert(  equal( string1, string4 ) );
console.assert(  equal( string1, string4 ) === equal.VALUE_AND_TYPE );
console.assert(  equal( string1, string5 ) );
console.assert(  equal( string1, string5 ) === equal.VALUE_AND_TYPE );
console.assert( !equal( string1, string6 ) );
console.assert(  equal( string1, string6 ) === equal.NOT_EQUAL );
console.assert(  equal( string6, string7 ) );
console.assert(  equal( string6, string7 ) === equal.VALUE_AND_TYPE );
console.log( '-- Ok' );

console.log( 'Number wrapper should be compared as a number' );
// jshint -W053
var number1 = new Number( 10.10 );
var number2 = number1;
var number3 = new Number( 20.20 );
var number4 = new Number( 10.10 );
// jshint +W053
var number5 = 10.10;
var number6 = 10;
var number7 = 10;
console.assert(  equal( number1, number2 ) );
console.assert(  equal( number1, number2 ) === equal.VALUE_AND_TYPE );
console.assert( !equal( number1, number3 ) );
console.assert(  equal( number1, number3 ) === equal.NOT_EQUAL );
console.assert(  equal( number1, number4 ) );
console.assert(  equal( number1, number4 ) === equal.VALUE_AND_TYPE );
console.assert(  equal( number1, number5 ) );
console.assert(  equal( number1, number5 ) === equal.VALUE_AND_TYPE );
console.assert( !equal( number1, number6 ) );
console.assert(  equal( number1, number6 ) === equal.NOT_EQUAL );
console.assert(  equal( number6, number7 ) );
console.assert(  equal( number6, number7 ) === equal.VALUE_AND_TYPE );
console.log( '-- Ok' );

console.log( 'Boolean wrapper should be compared as a boolean' );
// jshint -W053
var boolean1 = new Boolean( false );
var boolean2 = boolean1;
var boolean3 = new Boolean( true );
var boolean4 = new Boolean( false );
// jshint +W053
var boolean5 = false;
var boolean6 = true;
var boolean7 = true;
console.assert(  equal( boolean1, boolean2 ) );
console.assert(  equal( boolean1, boolean2 ) === equal.VALUE_AND_TYPE );
console.assert( !equal( boolean1, boolean3 ) );
console.assert(  equal( boolean1, boolean3 ) === equal.NOT_EQUAL );
console.assert(  equal( boolean1, boolean4 ) );
console.assert(  equal( boolean1, boolean4 ) === equal.VALUE_AND_TYPE );
console.assert(  equal( boolean1, boolean5 ) );
console.assert(  equal( boolean1, boolean5 ) === equal.VALUE_AND_TYPE );
console.assert( !equal( boolean1, boolean6 ) );
console.assert(  equal( boolean1, boolean6 ) === equal.NOT_EQUAL );
console.assert(  equal( boolean6, boolean7 ) );
console.assert(  equal( boolean6, boolean7 ) === equal.VALUE_AND_TYPE );
console.log( '-- Ok' );

console.log( 'Date should be compare with number when "nonStrict" option is true' );
var date5 = new Date();
var numDate = date5.valueOf();
console.assert( !equal( date5, numDate  ) );
console.assert(  equal( date5, numDate  ) === equal.NOT_EQUAL );
console.assert(  equal( date5, numDate, {nonStrict: true}  ) );
console.assert(  equal( date5, numDate, {nonStrict: true}  ) === equal.VALUE );
console.log( '-- Ok' );

console.log( 'Number amd String wrappers should be compared when "nonStrict" option is true' );
// jshint -W053
var number10 = new Number( 99 );
var number11 = 99;
var string10 = new String( "99" );
var string11 = "99";
// jshint +W053
console.assert( !equal( number10, string10 ) );
console.assert(  equal( number10, string10 ) === equal.NOT_EQUAL );
console.assert(  equal( number10, string10, {nonStrict: true} ) );
console.assert(  equal( number10, string10, {nonStrict: true} ) === equal.VALUE );
console.assert( !equal( number10, string11 ) );
console.assert(  equal( number10, string11 ) === equal.NOT_EQUAL );
console.assert(  equal( number10, string11, {nonStrict: true} ) );
console.assert(  equal( number10, string11, {nonStrict: true} ) === equal.VALUE );
console.log( '-- Ok' );

console.log( 'Two simple objects should be compared by its properties' );
var obj1 = {a: 0, b: 1, c: 3, d: 4, e: 5, f: 6, g: 7, h: 8, i: 9, j: 10, k: 11};
var obj2 = obj1;
var obj3 = {a: 1, b: 1, c: 3, d: 4, e: 5, f: 6, g: 7, h: 8, i: 9, j: 10, k: 11};
var obj4 = {a: 0, b: 1, c: 3, d: 4, e: 5, f: 6, g: 7, h: 8, i: 9, j: 10, m: 11};
var obj5 = {a: 0, b: 1, c: 3, d: 4, e: 5, f: 6, g: 7, h: 8, i: 9, j: 10, k: 11};
console.assert(  equal( obj1, obj2 ) );
console.assert(  equal( obj1, obj2 ) === equal.VALUE_AND_TYPE );
console.assert( !equal( obj1, obj3 ) );
console.assert(  equal( obj1, obj3 ) === equal.NOT_EQUAL );
console.assert( !equal( obj1, obj4 ) );
console.assert(  equal( obj1, obj4 ) === equal.NOT_EQUAL );
console.assert(  equal( obj1, obj5 ) );
console.assert(  equal( obj1, obj5 ) === equal.PROPERTIES_AND_TYPE );
console.log( '-- Ok' );

console.log( 'The object constructor should is revelant for the comparison' );
var emptyObject1 = {};
var emptyObject2 = emptyObject1;
var emptyObject3 = {a: null};
var emptyObject4 = Object.create( {} );
var emptyObject5 = Object.create( null );
console.assert(  equal( emptyObject1, emptyObject2 ) );
console.assert(  equal( emptyObject1, emptyObject2 ) === equal.VALUE_AND_TYPE );
console.assert( !equal( emptyObject1, emptyObject3 ) );
console.assert(  equal( emptyObject1, emptyObject3 ) === equal.NOT_EQUAL );
console.assert(  equal( emptyObject1, emptyObject4 ) );
console.assert(  equal( emptyObject1, emptyObject4 ) === equal.PROPERTIES_AND_TYPE );
console.assert( !equal( emptyObject1, emptyObject5 ) );
console.assert(  equal( emptyObject1, emptyObject5 ) === equal.NOT_EQUAL );
console.log( '-- Ok' );

console.log( 'Two deep objects should be compared by its properties' );
var nestedObject1  = {o1: {a: 1, b: true, c: 'hello', d: {n: [99]}}, o2: [0, 1, 2, 3]};
var nestedObject2  = nestedObject1;
var nestedObject3  = {o1: {a: 1, b: true, c: 'hello', d: {n: [100]}}, o2: [0, 1, 2, 3]};
var nestedObject4  = {o1: {a: 1, b: true, c: 'hello', d: {n: [99]}}, o2: [0, 1, 2, 3]};
var nestedObject5  = Object.create( null );
nestedObject5.o1   = {a: 1, b: true, c: 'hello'};
nestedObject5.o1.d = {n: [99]};
nestedObject5.o2   = [0, 1, 2, 3];
console.assert(  equal( nestedObject1, nestedObject2 ) );
console.assert(  equal( nestedObject1, nestedObject2 ) === equal.VALUE_AND_TYPE );
console.assert( !equal( nestedObject1, nestedObject3 ) );
console.assert(  equal( nestedObject1, nestedObject3 ) === equal.NOT_EQUAL );
console.assert(  equal( nestedObject1, nestedObject4 ) );
console.assert(  equal( nestedObject1, nestedObject4 ) === equal.PROPERTIES_AND_TYPE );
console.assert( !equal( nestedObject1, nestedObject5 ) );
console.assert(  equal( nestedObject1, nestedObject5 ) === equal.NOT_EQUAL );
console.log( '-- Ok' );

console.log( 'Two simple arrays should be compared by its content' );
var array1 = [0, 1, 3, 4, 5, 6, 7, 8, 9, 10, 11];
var array2 = array1;
var array3 = [0, 1, 3, 4, 5, 6, 7, 8, 9, 10, 10];
var array4 = [0, 1, 3, 4, 5, 6, 7, 8, 9, 10];
var array5 = [0, 1, 3, 4, 5, 6, 7, 8, 9, 10, 11];
console.assert(  equal( array1, array2 ) );
console.assert(  equal( array1, array2 ) === equal.VALUE_AND_TYPE );
console.assert( !equal( array1, array3 ) );
console.assert(  equal( array1, array3 ) === equal.NOT_EQUAL );
console.assert( !equal( array1, array4 ) );
console.assert(  equal( array1, array4 ) === equal.NOT_EQUAL );
console.assert(  equal( array1, array5 ) );
console.assert(  equal( array1, array5 ) === equal.PROPERTIES_AND_TYPE );
var tmpDate = new Date(  );
var multi1  = [0, true, false, tmpDate, [0, 1, 2, 3], {a: 1}, 'hello', [[true, false], [{b: 2}, {b: 3}]]];
var multi2  = multi1;
var multi3  = [0, true, false, tmpDate, [0, 1, 2, 3], {a: 1}, 'hello', [[true, false], [{b: 2}, {b: 4}]]];
var multi4  = [0, 1, 2, 3, 4, 5, 6, 7];
var multi5  = [0, true, false, tmpDate, [0, 1, 2, 3], {a: 1}, 'hello', [[true, false], [{b: 2}, {b: 3}]]];
console.assert(  equal( multi1, multi2 ) );
console.assert(  equal( multi1, multi2 ) === equal.VALUE_AND_TYPE );
console.assert( !equal( multi1, multi3 ) );
console.assert(  equal( multi1, multi3 ) === equal.NOT_EQUAL );
console.assert( !equal( multi1, multi4 ) );
console.assert(  equal( multi1, multi4 ) === equal.NOT_EQUAL );
console.assert(  equal( multi1, multi5 ) );
console.assert(  equal( multi1, multi5 ) === equal.PROPERTIES_AND_TYPE);
console.log( '-- Ok' );

console.log('Two arrays should be compared by its content and properties');
var arrObj1 = [ 1, 2, 3, 4, 5];
arrObj1.property = 'hello';
var arrObj2 = [ 1, 2, 3, 4, 5];
arrObj2.property = 'hello';
var arrObj3 = [1,2,3,4,5];
arrObj3.property = 'Bye';
var arrObj4 = [1,2,3,4,5];
console.assert(  equal( arrObj1, arrObj2 ) );
console.assert(  equal( arrObj1, arrObj2 ) === equal.PROPERTIES_AND_TYPE );
console.assert( !equal( arrObj1, arrObj3 ) );
console.assert( !equal( arrObj1, arrObj4 ) );
console.log('-- Ok');

console.log( 'Sparse array must be managed without problems' );
// jshint -W128
var sparse1 = [0, , 3, , 5, , 7, , 9, , 11];
// jshint +W128
var sparse2 = sparse1;
var sparse3 = [0, 1, 3, 4, 5, 6, 7, 8, 9, 10];
var sparse4 = [0, undefined, 3, undefined, 5, undefined, 7, undefined, 9, undefined, 11];
var sparse5 = [0, 1, 3, 4, 5, 6, 7, 8, 9, 10, 11];
delete sparse5[1];
delete sparse5[3];
delete sparse5[5];
delete sparse5[7];
delete sparse5[9];
console.assert(  equal( sparse1, sparse2 ) );
console.assert(  equal( sparse1, sparse2 ) === equal.VALUE_AND_TYPE );
console.assert( !equal( sparse1, sparse3 ) );
console.assert(  equal( sparse1, sparse3 ) === equal.NOT_EQUAL );
console.assert( !equal( sparse1, sparse4 ) );
console.assert(  equal( sparse1, sparse4 ) === equal.NOT_EQUAL );
console.assert(  equal( sparse1, sparse5 ) );
console.assert(  equal( sparse1, sparse5 ) === equal.PROPERTIES_AND_TYPE );
console.log( '-- Ok' );

console.log( 'An Array and an Array Like are equal only when nonStrict options is true' );
var array10    = [0, 1, 2];
var arrayLike1 = {'0': 0, '1': 1, '2': 2};
Object.defineProperty( arrayLike1, 'length', {enumerable: false, configurable: false, writable: true, value: 3} );
var arrayLike2 = {'0': 0, '1': 1, '2': 2, 'length': 3};
console.assert( !equal( array10, arrayLike1 ) );
console.assert(  equal( array10, arrayLike1 ) === equal.NOT_EQUAL );
console.assert(  equal( array10, arrayLike1, {nonStrict: true} ) );
console.assert(  equal( array10, arrayLike1, {nonStrict: true} ) === equal.PROPERTIES );
console.assert( !equal( array10, arrayLike2, {nonStrict: true} ) );
console.assert(  equal( array10, arrayLike2, {nonStrict: true} ) === equal.NOT_EQUAL );
console.log( '-- Ok' );

if (typeof process !== 'undefined' && typeof process.exit !== 'undefined') {
    process.exit( 0 );
}